- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: What is your username?
    private: false
  - name: password
    prompt: What is your username?
    private: true
  tasks:
  -name: Print credentials
  ansible.builtin.debug:
    msg: "Hello, username is {{ username }}, password is {{ password}}"